### PR TITLE
Ensure we indent switch statements correctly

### LINKED ISSUE #40: case keywords inside switch is not indenting correctly
The `case` and `default` keywords are not indented correctly (they are moved to the same column as the containing `switch` keyword). Also, the block inside a case is started at that column, and not in a further indentation as I would expect. (But perhaps my expectations are wrong?)

I'm using groovy-mode-20170323.817

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes #40.

### CODE REVIEW

**Comment by russel** [comment]
Does this cover the case where people do "x? y: z" or "case X :" or is it assuming a specific use of space?

**Comment by Wilfred** [comment]
`case x :` should work because we just look for a line ending with `:` inside a `switch` block.

`x? y: z` should also work because the line doesn't end with `:`.

I agree that logic like this is tricky though. I believe the logic here works in the large majority of cases (since it's line oriented, it may be possible to get incorrect indentation on large multiline expressions) and so it's a big improvement over the current state of the code.

**Comment by russel** [comment]
I think I am in "irritated" mode, so apologies, but do you think we should put tests in for these cases?

**Comment by Wilfred** [comment]
@russel added more tests, and fixed the issues they exposed :)

**Pull request merged**
