### PR TITLE
Change groovy-mode to be a standalone mode.

### LINKED ISSUE #11: Can't load groovy-mode : File mode specification error: (void-function set-difference)
I installed groovy-mode via melpa (20141209) today.
I opened a simple groovy file:

``` groovy
class Main {
    static void main(String... args) {
        println 'Hello'
    }
}
```

groovy-mode should have fired up but failed:
`File mode specification error: (void-function set-difference)`

During the installation with melpa, there was that error:

``` elisp

Compiling file /home/paraita/.emacs.d/elpa/groovy-mode-20141209.1133/groovy-electric.el at Sun May 10 00:37:58 2015
Entering directory `/home/paraita/.emacs.d/elpa/groovy-mode-20141209.1133/'
groovy-electric.el:55:1:Error: Symbol's function definition is void: set-difference

Compiling file /home/paraita/.emacs.d/elpa/groovy-mode-20141209.1133/groovy-mode.el at Sun May 10 00:37:58 2015
groovy-mode.el:354:1:Error: Symbol's function definition is void: set-difference

Compiling file /home/paraita/.emacs.d/elpa/groovy-mode-20141209.1133/inf-groovy.el at Sun May 10 00:37:58 2015
inf-groovy.el:51:1:Error: Symbol's function definition is void: set-difference
```

but it installed anyway.

Forcing the `(require 'cl)` in `groovy-mode.el` solved my problem.

I am using Emacs 24.5.1 on Archlinux x86_64
and yeah I'm aware of the [cc-mode bug](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18845).

### PR DESCRIPTION
**Pull request by Wilfred**
As discussed in https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/issues/26#issuecomment-283393650 I'm having a go at modifying groovy-mode so it doesn't depend on cc-mode.

This has fixed all of the open highlighting bugs in this repo, and it should fix #11 too.

Let me know what you think.

Edit: now includes indentation logic.

### CODE REVIEW

**Comment by russel** [comment]
I think for the moment I should merge this into a new branch in this mainline repository. People willing to test the mode (including me) can then use the branch rather than master. This would entail me merging this pull request on my clone, pushing to mainline, and then apparently rejecting this pull request.

Does that make sense and seem reasonable?

**Comment by Wilfred** [comment]
Yep, that makes sense, thanks.

**Comment by Wilfred** [comment]
@russel I've added indentation logic, so as far as I'm concerned this is done! :)

**Comment by russel** [comment]
As agreed I have created a new branch in this mainline repository with this changeset in and so I am rejecting this pull request (since it is posted against master). I will amend the README.md in master and post an email to the Groovy mailing list to see if we can get people to use the new version and report back.

**Pull request closed without merging**
