### PR TITLE
Readme change: Add note for Windows users

### PR DESCRIPTION
**Pull request by blackorzar**
Add note for Windows users, suggest adding the code to .emacs and formating.

### CODE REVIEW

**Comment by russel** [comment]
Why is it that Windows users have to use MELPA "unstable", they cannot use stable?

**Comment by blackorzar** [comment]
Hello Russel! 
It was the way i was able to install groovy-mode on Windows but maybe the groovy-mode in Melpa stable is broken. Please go to https://stable.melpa.org and  search for groovy-mode and it doesn't return any result. while http://melpa.org shows the groovy-mode in the search results.

**Comment by russel** [comment]
OK the problem here is that this mode is not appearing in MELPA Stable, which is covered by #21. I will close this as a duplicate for now.

**Comment by russel** [comment]
Groovy mode is now in MELPA Stable as well as MELPA.

**Pull request closed without merging**
